{"data":{"mdx":{"frontmatter":{"title":"Handling Unexpected Error with React and Redux","date":"September 4, 2018"},"body":"var _excluded = [\"components\"];\n\nfunction _extends() { _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; }; return _extends.apply(this, arguments); }\n\nfunction _objectWithoutProperties(source, excluded) { if (source == null) return {}; var target = _objectWithoutPropertiesLoose(source, excluded); var key, i; if (Object.getOwnPropertySymbols) { var sourceSymbolKeys = Object.getOwnPropertySymbols(source); for (i = 0; i < sourceSymbolKeys.length; i++) { key = sourceSymbolKeys[i]; if (excluded.indexOf(key) >= 0) continue; if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue; target[key] = source[key]; } } return target; }\n\nfunction _objectWithoutPropertiesLoose(source, excluded) { if (source == null) return {}; var target = {}; var sourceKeys = Object.keys(source); var key, i; for (i = 0; i < sourceKeys.length; i++) { key = sourceKeys[i]; if (excluded.indexOf(key) >= 0) continue; target[key] = source[key]; } return target; }\n\n/* @jsxRuntime classic */\n\n/* @jsx mdx */\nvar _frontmatter = {\n  \"title\": \"Handling Unexpected Error with React and Redux\",\n  \"date\": \"2018-09-04\",\n  \"categories\": [\"react\", \"redux\"]\n};\nvar layoutProps = {\n  _frontmatter: _frontmatter\n};\nvar MDXLayout = \"wrapper\";\nreturn function MDXContent(_ref) {\n  var components = _ref.components,\n      props = _objectWithoutProperties(_ref, _excluded);\n\n  return mdx(MDXLayout, _extends({}, layoutProps, props, {\n    components: components,\n    mdxType: \"MDXLayout\"\n  }), mdx(\"p\", null, \"Regardless of how professional developer you are, there always will be an exception that will slip between your fingers, or should I say between your lines of code. These errors that bubble up the stack are called unexpected error. While it is always preferable to catch the error as close as possible of where the exception is thrown, it is still better to catch them at a high level. In the web world, it gives an opportunity to have a generic message to the user gracefully. It also provides an open door to collect the unexpected error and act before having any of your customers reach you.\"), mdx(\"p\", null, \"There are three places where you need to handle unexpected errors in a stack using React and Redux. The first one is at React level. An unexpected error can occur in a render method for example. The second level is during the mapping between Redux and React. The error occurs when we move data from the Redux's store to the React's property of the connected component. The third level is an error in the chain of middlewares. The last one will bubble up through the stack of middleware and explode where the action was dispatched. Let's see how we can handle these three cases in your application.\"), mdx(\"h2\", null, \"React Unhandled Exception\"), mdx(\"p\", null, \"Since version 16, React simplified the capture of error by introducing the lifecycle function \", mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"componentDidCatch\"), \". It is a function like \", mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"render\"), \" or \", mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"componentShouldUpdate\"), \" that come with the framework. The \", mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"componentDidCatch\"), \" is triggered when an exception go thrown any children of the component. The detail about what it covers is crucial. You must have a component that englobes most of your application. If you are using React-Router and would like to keep the web application with the same URL and have the menus to stay in place, this can be tricky. The idea is to create a new component with the sole purpose of wrapping all top route components. Having a single component to handle the unexpected error is interesting. It is simple, easy to test, with a cohesive and single task.\"), mdx(\"pre\", null, mdx(\"code\", {\n    parentName: \"pre\",\n    \"className\": \"language-typescript\"\n  }, \"export interface ErrorBoundaryStates { hasError: boolean; } \\nexport class ErrorBoundary extends React.Component<ErrorBoundaryProps, ErrorBoundaryStates> { \\n  constructor(props: ErrorBoundaryProps) { \\n    super(props); \\n    this.state = { hasError: false }; \\n  }\\n\\n  public componentDidCatch(error: Error, errorInfo: ErrorInfo): void { \\n    this.setState({ hasError: true }); \\n    YourLoggingSystem.track(error, \\\"ErrorBoundary\\\", { errorInfo: errorInfo }); \\n  }\\n\\n  public render() { \\n    if (this.state.hasError) { \\n      return <div className=\\\"ErrorBoundary\\\"> The application crashed. Sorry! </div>; \\n    } \\n    return this.props.children; \\n  } \\n} \\n\")), mdx(\"p\", null, \"However, with React-Router, every route is assigned as property. The property is an excellent opportunity to create a function that returns the React class.\"), mdx(\"pre\", null, mdx(\"code\", {\n    parentName: \"pre\",\n    \"className\": \"language-typescript\"\n  }, \"// CODE IN YOUR TOP APP CONTAINER:\\n\\n// Constructor: \\nthis.page1Component = withErrorBoundary()(Page1Component)); \\n\\n// Render: \\n<Route path={Routes.PAGE_1} component={this.page1Component} />\\n\\n// UTILITY FUNCTION \\nexport const withErrorBoundary = () => <P extends object>(Component: React.ComponentType<P>) \\n  => class WithErrorBoundary extends React.Component<P> { \\n    render() { \\n      return <ErrorBoundary}><Component {...this.props} /></ErrorBoundary>; \\n    } \\n}; \\n\")), mdx(\"h2\", null, \"Redux Mapping Unhandled Exception\"), mdx(\"p\", null, \"This section will be short because it is covered with React. However, I wanted to clarify that this can be tricky if you are not doing exactly like the pattern I described. For instance, if you are wrapping the \", mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"withErrorBoundary\"), \" not at the initialization of the route but directly when you connect -- it will not work. For example, the code below does not work as you might expect. The reason is that the error is bound to the component but not to the code being bound by the React-Connect.\"), mdx(\"pre\", null, mdx(\"code\", {\n    parentName: \"pre\",\n    \"className\": \"language-typescript\"\n  }, \"export default connect<ModelPage1, DispatchPage1, {}, {}, AppReduxState>( (s) => \\n  orgMappers.mapStateToProps(s), (s) => orgMappers.mapDispatchToProps(s) )(WithErrorBoundary()(Page1Component)); \\n\")), mdx(\"p\", null, \"Outside of the initial solution proposed, it is also valid to wrap the \", mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"connect\"), \" to have the desired effect of receiving the error in the \", mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"componentDidCatch\"), \" of the \", mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"ErrorBoundary\"), \". I prefer the former solution because it does not coerce the ErrorBoundary with the component forever.\"), mdx(\"pre\", null, mdx(\"code\", {\n    parentName: \"pre\",\n    \"className\": \"language-typescript\"\n  }, \"export default WithErrorBoundary(connect<ModelPage1, DispatchPage1, {}, {}, AppReduxState>( (s) => \\n  orgMappers.mapStateToProps(s), (s) => orgMappers.mapDispatchToProps(s) )(Page1Component)); \\n\")), mdx(\"h2\", null, \"Redux Middleware Unhandled Exception\"), mdx(\"p\", null, \"The last portion of the code that needs to have a catch-all is the middleware. The solution goes with the Redux's middleware concept which is to leverage function that calls themselves. The idea is to have one of the first function, middleware, to be a big try-catch.\"), mdx(\"pre\", null, mdx(\"code\", {\n    parentName: \"pre\",\n    \"className\": \"language-typescript\"\n  }, \"const appliedMiddleware = applyMiddleware( thunk, unhandledExceptionMiddleware, middleware1, middleware2, middleware3, middleware4 );\\n\\n// Excerpt of the middleware: return (api: MiddlewareAPI<Dispatch, AppReduxState>) => \\n  (next: Dispatch) => \\n    (action: Actions): any => { \\n      try { \\n        return next(action); \\n      } \\n      catch (error) { \\n        YourLoggingSystem.track(error, \\\"Unhandled Exception in Middleware\\\"); \\n        return next(/*Insert here an action that will render something to the UI to indicate to the user that an error occured*/); \\n      } \\n    }; \\n\")), mdx(\"h2\", null, \"Summary\"), mdx(\"p\", null, \"Handling errors in a React and Redux world require code to be in a particular way. At this day, the documentation is not very clear. Mostly because there is a clear separation between React, Redux, Redux-Connect, and React-Router. While it is very powerful to have each element of the puzzle separated, this comes with the price that the integration is in a gray area. Hopefully, this article uncovers some mystery around how to collection unhandled errors and removed confusion with the particular case of why mapping error can throw error through the React mechanism when not positioned at the right place.\"));\n}\n;\nMDXContent.isMDXComponent = true;"}},"pageContext":{"id":"1864f8dc-b404-51b4-9769-9d936c091176","slug":"2018/handling-unexpected-error-with-react-and-redux","__params":{"slug":"2018"}}}